### PR TITLE
Changes To A 2_by_4 Decoder

### PR DESCRIPTION
**Pull request by Agatha22**

### CODE REVIEW

**Comment by Muriukidavid** [comment]
can't merge, you have conflicts. Rectify and resubmit

**Comment by Agatha22** [comment]
Hi, i've submitted this four times already would you please tell me what this conflicts are because  it works just fine on my side.

**Comment by Muriukidavid** [comment]
Its your repo not mine, how can you ask me what the conflicts are? I have no idea. You on the other hand have everything. You have access to the class repo,  do a git pull from it. I always say, do a git pull before pushing. If there are conflicts, it will tell you in the pull output. There is no way I can tell why your repo is dirty remotely. May be you should come and consult in person if you are stuck :cactus:

**Comment by Agatha22** [comment]
Okay...thanks

**Comment by Agatha22** [comment]
Hi, i sent my assignments on github sometime back & have not gotten any feedback for sometime. Incase you forgot, please check on it so i know if i still need to do something or if its ready for merging. Thank you.

**Comment by Muriukidavid** [comment]
Alright, checking just now...

**Pull request closed without merging**
